version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U","api"]
      interval: 5s
      retries: 5
    ports:
      - "5433:5432"

  migrate:
    build:
      context: .
      dockerfile: apps/service/Dockerfile
    command: [
      "npx","prisma","migrate","deploy",
      "--schema=./prisma/schema.prisma"
    ]
    environment:
      DATABASE_URL: postgres://api:api@db:5432/api
    depends_on:
      db: { condition: service_healthy }

  app:
    build:
      context: .
      dockerfile: apps/service/Dockerfile
    depends_on:
      - migrate
      - db
    environment:
      DATABASE_URL: postgres://api:api@db:5432/api
      ADMIN_TOKEN: super-secret-value
      PORT: "3000"
    ports:
      - "3000:3000"

volumes:
  dbdata:
