FROM node:20-alpine AS builder
WORKDIR /usr/src/frontend
COPY package*.json tsconfig.json vite.config.ts ./
RUN npm ci
COPY src ./src
COPY index.html .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /usr/src/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
